<a href="https://colab.research.google.com/github/hkrishnanrt/DSA-Activities/blob/main/ETL_Case_Study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np

 Load the dataset into a DataFrame

In [9]:
data=pd.read_csv("/content/all_month.csv")
df=pd.DataFrame(data)
df

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2025-09-19T16:56:43.610Z,32.998833,-116.231833,7.2900,1.12,ml,43.0,48.0,0.07458,0.1900,...,2025-09-19T17:00:14.218Z,"19 km SSW of Ocotillo Wells, CA",earthquake,0.190000,0.560000,0.191000,28.0,automatic,ci,ci
1,2025-09-19T16:44:41.040Z,33.698667,-116.821833,16.9900,0.80,ml,20.0,87.0,0.07183,0.1400,...,2025-09-19T16:48:10.654Z,"9 km SE of Valle Vista, CA",earthquake,0.310000,0.550000,0.261000,19.0,automatic,ci,ci
2,2025-09-19T16:11:32.749Z,53.268200,161.342900,10.0000,4.50,mb,21.0,134.0,1.64000,0.9600,...,2025-09-19T16:58:55.040Z,"183 km E of Petropavlovsk-Kamchatsky, Russia",earthquake,11.520000,1.926000,0.118000,21.0,reviewed,us,us
3,2025-09-19T16:08:22.517Z,31.122000,-103.736000,4.5162,1.60,ml,14.0,61.0,0.10000,0.6000,...,2025-09-19T17:02:35.233Z,"15 km N of Balmorhea, Texas",earthquake,0.000000,1.544627,0.100000,11.0,automatic,tx,tx
4,2025-09-19T16:05:55.210Z,56.790500,-158.451000,12.6900,0.51,ml,5.0,313.0,0.09334,0.0900,...,2025-09-19T16:30:23.560Z,"53 km N of Chignik Lagoon, Alaska",earthquake,0.920000,1.300000,0.156866,5.0,reviewed,av,av
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5287,2025-09-03T09:10:05.366Z,64.726400,-149.148400,11.4000,0.70,ml,NaN,NaN,NaN,0.3600,...,2025-09-03T09:12:17.241Z,"13 km N of Four Mile Road, Alaska",earthquake,NaN,0.800000,NaN,NaN,automatic,ak,ak
5288,2025-09-03T09:05:35.777Z,32.001000,-103.811000,6.8561,1.30,ml,14.0,74.0,0.00000,0.1000,...,2025-09-03T13:09:24.761Z,"34 km SE of Malaga, New Mexico",earthquake,0.428218,0.671439,0.200000,6.0,reviewed,tx,tx
5289,2025-09-03T09:00:36.235Z,41.189600,-116.724100,5.5000,1.90,ml,6.0,159.4,0.31300,0.1588,...,2025-09-09T21:36:37.993Z,"55 km NE of Valmy, Nevada",earthquake,NaN,2.900000,0.370000,4.0,reviewed,nn,nn
5290,2025-09-03T08:45:15.940Z,46.851000,-121.765333,-2.7300,0.45,ml,19.0,70.0,0.01896,0.0800,...,2025-09-04T19:07:22.430Z,"22 km ENE of Ashford, Washington",earthquake,0.190000,0.370000,0.168939,12.0,reviewed,uw,uw
5291,2025-09-03T08:44:09.350Z,38.505167,-112.899667,2.1100,1.09,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Identify number of records and unique locations

In [10]:
print(f"Number of rows : {len(df)}")
print(f"Unique locations : {df['place'].unique()}")

Number of rows : 5292
Unique locations : ['19 km SSW of Ocotillo Wells, CA' '9 km SE of Valle Vista, CA'
 '183 km E of Petropavlovsk-Kamchatsky, Russia' ...
 '3 km E of Twin Bridges, Montana' '13 km N of Four Mile Road, Alaska' nan]

 Print top 5 rows and column names

In [11]:
df.head()

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2025-09-19T16:56:43.610Z,32.998833,-116.231833,7.2900,1.12,ml,43.0,48.0,0.07458,0.19,...,2025-09-19T17:00:14.218Z,"19 km SSW of Ocotillo Wells, CA",earthquake,0.19,0.560000,0.191000,28.0,automatic,ci,ci
1,2025-09-19T16:44:41.040Z,33.698667,-116.821833,16.9900,0.80,ml,20.0,87.0,0.07183,0.14,...,2025-09-19T16:48:10.654Z,"9 km SE of Valle Vista, CA",earthquake,0.31,0.550000,0.261000,19.0,automatic,ci,ci
2,2025-09-19T16:11:32.749Z,53.268200,161.342900,10.0000,4.50,mb,21.0,134.0,1.64000,0.96,...,2025-09-19T16:58:55.040Z,"183 km E of Petropavlovsk-Kamchatsky, Russia",earthquake,11.52,1.926000,0.118000,21.0,reviewed,us,us
3,2025-09-19T16:08:22.517Z,31.122000,-103.736000,4.5162,1.60,ml,14.0,61.0,0.10000,0.60,...,2025-09-19T17:02:35.233Z,"15 km N of Balmorhea, Texas",earthquake,0.00,1.544627,0.100000,11.0,automatic,tx,tx
4,2025-09-19T16:05:55.210Z,56.790500,-158.451000,12.6900,0.51,ml,5.0,313.0,0.09334,0.09,...,2025-09-19T16:30:23.560Z,"53 km N of Chignik Lagoon, Alaska",earthquake,0.92,1.300000,0.156866,5.0,reviewed,av,av

In [12]:
print(data.columns)

Index(['time', 'latitude', 'longitude', 'depth', 'mag', 'magType', 'nst',
       'gap', 'dmin', 'rms', 'net', 'id', 'updated', 'place', 'type',
       'horizontalError', 'depthError', 'magError', 'magNst', 'status',
       'locationSource', 'magSource'],
      dtype='object')

Convert time to datetime

In [13]:
df['time']=pd.to_datetime(df['time'])
df['time'].dtype

datetime64[ns, UTC]

 Drop records with missing latitude, longitude, mag

In [14]:
df=df.dropna(subset=['latitude','longitude','mag'])

Filter only earthquakes with magnitude >= 4.0

In [15]:
df[df['mag']>=4.0]

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
2,2025-09-19 16:11:32.749000+00:00,53.2682,161.3429,10.000,4.5,mb,21.0,134.0,1.640,0.96,...,2025-09-19T16:58:55.040Z,"183 km E of Petropavlovsk-Kamchatsky, Russia",earthquake,11.52,1.926,0.118,21.0,reviewed,us,us
8,2025-09-19 15:45:34.839000+00:00,52.9359,161.2812,10.000,5.9,mww,79.0,72.0,1.593,1.11,...,2025-09-19T16:37:04.040Z,"178 km E of Petropavlovsk-Kamchatsky, Russia",earthquake,8.22,1.872,0.048,41.0,reviewed,us,us
10,2025-09-19 15:37:33.723000+00:00,52.8113,160.5027,35.000,5.2,mb,59.0,123.0,1.142,0.69,...,2025-09-19T15:52:34.040Z,"129 km ESE of Petropavlovsk-Kamchatsky, Russia",earthquake,8.67,1.924,0.024,559.0,reviewed,us,us
20,2025-09-19 14:55:29.171000+00:00,51.4220,157.7944,84.495,5.9,mww,62.0,116.0,1.688,0.89,...,2025-09-19T15:49:02.040Z,"90 km E of Ozernovskiy, Russia",earthquake,9.28,7.505,0.093,11.0,reviewed,us,us
25,2025-09-19 14:23:37.509000+00:00,52.4905,160.9460,10.000,5.1,mb,38.0,154.0,1.494,0.84,...,2025-09-19T14:41:45.040Z,"168 km ESE of Petropavlovsk-Kamchatsky, Russia",earthquake,10.65,1.934,0.034,276.0,reviewed,us,us
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5226,2025-09-03 13:45:36.482000+00:00,-20.5304,-177.8387,569.035,4.7,mb,62.0,74.0,4.771,0.49,...,2025-09-03T14:03:43.040Z,"273 km WNW of Houma, Tonga",earthquake,9.92,8.144,0.062,83.0,reviewed,us,us
5243,2025-09-03 12:41:35.910000+00:00,-12.1271,166.5085,103.554,4.6,mb,32.0,143.0,3.368,0.78,...,2025-09-03T13:05:20.040Z,"173 km SSE of Lata, Solomon Islands",earthquake,12.03,8.929,0.105,27.0,reviewed,us,us
5252,2025-09-03 12:03:47.123000+00:00,54.0397,-159.7695,10.000,4.3,mb,30.0,167.0,0.800,0.54,...,2025-09-04T01:36:35.504Z,"151 km SSE of Sand Point, Alaska",earthquake,5.28,1.956,0.148,13.0,reviewed,us,us
5271,2025-09-03 10:18:41.533000+00:00,-1.9569,139.1728,20.901,4.7,mb,33.0,82.0,1.186,0.69,...,2025-09-03T10:54:00.040Z,"177 km WNW of Abepura, Indonesia",earthquake,7.64,5.750,0.108,26.0,reviewed,us,us
5276,2025-09-03 09:51:43.168000+00:00,-7.7403,127.6824,133.380,4.5,mb,16.0,148.0,3.925,0.47,...,2025-09-03T10:16:27.040Z,"114 km NE of Lospalos, Timor Leste",earthquake,11.10,13.398,0.140,15.0,reviewed,us,us

 Add a column day_of_week from time

In [16]:
df['day_of_week']=df['time'].dt.day_name()
df

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource,day_of_week
0,2025-09-19 16:56:43.610000+00:00,32.998833,-116.231833,7.2900,1.12,ml,43.0,48.0,0.07458,0.1900,...,"19 km SSW of Ocotillo Wells, CA",earthquake,0.190000,0.560000,0.191000,28.0,automatic,ci,ci,Friday
1,2025-09-19 16:44:41.040000+00:00,33.698667,-116.821833,16.9900,0.80,ml,20.0,87.0,0.07183,0.1400,...,"9 km SE of Valle Vista, CA",earthquake,0.310000,0.550000,0.261000,19.0,automatic,ci,ci,Friday
2,2025-09-19 16:11:32.749000+00:00,53.268200,161.342900,10.0000,4.50,mb,21.0,134.0,1.64000,0.9600,...,"183 km E of Petropavlovsk-Kamchatsky, Russia",earthquake,11.520000,1.926000,0.118000,21.0,reviewed,us,us,Friday
3,2025-09-19 16:08:22.517000+00:00,31.122000,-103.736000,4.5162,1.60,ml,14.0,61.0,0.10000,0.6000,...,"15 km N of Balmorhea, Texas",earthquake,0.000000,1.544627,0.100000,11.0,automatic,tx,tx,Friday
4,2025-09-19 16:05:55.210000+00:00,56.790500,-158.451000,12.6900,0.51,ml,5.0,313.0,0.09334,0.0900,...,"53 km N of Chignik Lagoon, Alaska",earthquake,0.920000,1.300000,0.156866,5.0,reviewed,av,av,Friday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5287,2025-09-03 09:10:05.366000+00:00,64.726400,-149.148400,11.4000,0.70,ml,NaN,NaN,NaN,0.3600,...,"13 km N of Four Mile Road, Alaska",earthquake,NaN,0.800000,NaN,NaN,automatic,ak,ak,Wednesday
5288,2025-09-03 09:05:35.777000+00:00,32.001000,-103.811000,6.8561,1.30,ml,14.0,74.0,0.00000,0.1000,...,"34 km SE of Malaga, New Mexico",earthquake,0.428218,0.671439,0.200000,6.0,reviewed,tx,tx,Wednesday
5289,2025-09-03 09:00:36.235000+00:00,41.189600,-116.724100,5.5000,1.90,ml,6.0,159.4,0.31300,0.1588,...,"55 km NE of Valmy, Nevada",earthquake,NaN,2.900000,0.370000,4.0,reviewed,nn,nn,Wednesday
5290,2025-09-03 08:45:15.940000+00:00,46.851000,-121.765333,-2.7300,0.45,ml,19.0,70.0,0.01896,0.0800,...,"22 km ENE of Ashford, Washington",earthquake,0.190000,0.370000,0.168939,12.0,reviewed,uw,uw,Wednesday
5291,2025-09-03 08:44:09.350000+00:00,38.505167,-112.899667,2.1100,1.09,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wednesday

Create a column severity_level based on magnitude:
○ <4.0: "Low"
○ 4.0 - 6.0: "Moderate"
○ 6.0+: "High"

In [17]:
df['Severity_Level']=np.where(df['mag']<4.0,'Low',np.where((df['mag']>=4) & (df['mag']<=6),'Moderate','High'))
df

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource,day_of_week,Severity_Level
0,2025-09-19 16:56:43.610000+00:00,32.998833,-116.231833,7.2900,1.12,ml,43.0,48.0,0.07458,0.1900,...,earthquake,0.190000,0.560000,0.191000,28.0,automatic,ci,ci,Friday,Low
1,2025-09-19 16:44:41.040000+00:00,33.698667,-116.821833,16.9900,0.80,ml,20.0,87.0,0.07183,0.1400,...,earthquake,0.310000,0.550000,0.261000,19.0,automatic,ci,ci,Friday,Low
2,2025-09-19 16:11:32.749000+00:00,53.268200,161.342900,10.0000,4.50,mb,21.0,134.0,1.64000,0.9600,...,earthquake,11.520000,1.926000,0.118000,21.0,reviewed,us,us,Friday,Moderate
3,2025-09-19 16:08:22.517000+00:00,31.122000,-103.736000,4.5162,1.60,ml,14.0,61.0,0.10000,0.6000,...,earthquake,0.000000,1.544627,0.100000,11.0,automatic,tx,tx,Friday,Low
4,2025-09-19 16:05:55.210000+00:00,56.790500,-158.451000,12.6900,0.51,ml,5.0,313.0,0.09334,0.0900,...,earthquake,0.920000,1.300000,0.156866,5.0,reviewed,av,av,Friday,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5287,2025-09-03 09:10:05.366000+00:00,64.726400,-149.148400,11.4000,0.70,ml,NaN,NaN,NaN,0.3600,...,earthquake,NaN,0.800000,NaN,NaN,automatic,ak,ak,Wednesday,Low
5288,2025-09-03 09:05:35.777000+00:00,32.001000,-103.811000,6.8561,1.30,ml,14.0,74.0,0.00000,0.1000,...,earthquake,0.428218,0.671439,0.200000,6.0,reviewed,tx,tx,Wednesday,Low
5289,2025-09-03 09:00:36.235000+00:00,41.189600,-116.724100,5.5000,1.90,ml,6.0,159.4,0.31300,0.1588,...,earthquake,NaN,2.900000,0.370000,4.0,reviewed,nn,nn,Wednesday,Low
5290,2025-09-03 08:45:15.940000+00:00,46.851000,-121.765333,-2.7300,0.45,ml,19.0,70.0,0.01896,0.0800,...,earthquake,0.190000,0.370000,0.168939,12.0,reviewed,uw,uw,Wednesday,Low
5291,2025-09-03 08:44:09.350000+00:00,38.505167,-112.899667,2.1100,1.09,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wednesday,Low

Count number of earthquakes per place

In [18]:
df.groupby('place').size()

place
0 km  of The Geysers, CA            1
0 km ENE of The Geysers, CA         1
0 km ESE of Indios, Puerto Rico     1
0 km N of Greenback, Tennessee      1
0 km N of Howardville, Missouri     1
                                   ..
northern Mid-Atlantic Ridge         1
off the coast of Oregon             1
south of Africa                     2
south of the Fiji Islands           2
southeast of the Loyalty Islands    1
Length: 3077, dtype: int64

 Compute average magnitude and max depth per day

In [19]:
df.groupby(df['time'].dt.date).agg(avg_magnitude=('mag','mean'),max_depth=('depth','max'))

            avg_magnitude  max_depth
time
2025-09-03       1.659385    569.035
2025-09-04       1.581115    392.952
2025-09-05       1.348804    550.584
2025-09-06       1.322879    568.998
2025-09-07       1.421466    334.573
2025-09-08       1.545601    590.647
2025-09-09       1.529886    221.643
2025-09-10       1.429346    259.049
2025-09-11       1.426633    136.006
2025-09-12       1.370329    564.825
2025-09-13       1.425770    563.514
2025-09-14       1.275838    220.479
2025-09-15       1.355342    639.511
2025-09-16       1.263712    585.524
2025-09-17       1.173780    130.200
2025-09-18       1.927752    124.428
2025-09-19       2.099534    149.469

● Save:
○ Cleaned dataset to cleaned_earthquakes.csv
○ Summary data to earthquake_summary.csv

In [20]:
df.to_csv('Cleaned_earthquakes.csv',index=False)

In [40]:
df1=pd.read_csv('Cleaned_earthquakes.csv')
import pandas as pd


df1['time'] = pd.to_datetime(df1['time'], format='mixed')

summary = df1.groupby(df1['time'].dt.date).agg(
    avg_magnitude=('mag', 'mean'),
    max_depth=('depth', 'max')
).reset_index()

summary.to_csv("earthquake_summary.csv", index=False)

print(summary.head())

         time  avg_magnitude  max_depth
0  2025-09-03       1.659385    569.035
1  2025-09-04       1.581115    392.952
2  2025-09-05       1.348804    550.584
3  2025-09-06       1.322879    568.998
4  2025-09-07       1.421466    334.573

Store into SQLite table

In [56]:
import sqlite3
conn=sqlite3.connect('eathquakes.db')
df.to_sql("Earthquakes", conn, if_exists="replace", index=False)
summary.to_sql('Earthquake_summary',conn,if_exists='replace',index=False)
tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn)
print(tables)
conn.close()

                 name
0         Earthquakes
1  Earthquake_summary

A short explanation of process

1.Extract
* Loaded records from all_month.csv
* Columns include time,lattitude,longitude,depth,mag etc

2.Transform
* Dropped rows with missing latitude, longitude, or mag.
  filtered for magnitude ≥ 4.0.
* Converted time to datetime and added day_of_week.
* Added severity_level column:
<4.0: Low
4.0–6.0: Moderate
6.0+: High
* Counted earthquakes per place.
* Computed average magnitude and maximum depth per day.  

3.Load
* Cleaned dataset saved: Cleaned_earthquakes.csv
* Summary data saved: earthquake_summary.csv
* Stored cleaned data in an SQLite database → table:        earthquakes (earthquakes.db).

Insight:

Moderate earthquakes (4.0–6.0) dominate the dataset.